config/routes.rb
Rails.application.routes.draw do
  resources :alerts
  get 'games/decide_game_view' => 'games#decide_game_view', as: :decide_game_view
  resources :games
  resources :game_hitting_stats
  resources :game_pitching_stats
  resources :locations
  resources :players
  get 'welcome/index'

  get 'welcome/about'

  resources :users do
    resources :players
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :teams do
    resources :notes
  end

  namespace :api do
    match '/texts', to: 'texts#preflight', via: [:options]
    resources :texts, only: [:create]

    match '/keepscore/teams', to: 'keep_scores#preflight', via: [:options]
    get 'keepscore/teams' => 'keep_scores#get_teams', as: :get_teams

    match '/keepscore/roster', to: 'keep_scores#preflight', via: [:options]
    get 'keepscore/roster' => 'keep_scores#get_roster', as: :get_roster

    match '/keepscore/post_game_stats', to: 'keep_scores#preflight', via: [:options]
    post 'keepscore/post_game_stats' => 'keep_scores#post_game_stats', as: :post_game_stats

  end

  mount ActionCable.server, at: '/cable'
  root 'welcome#index'
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  belongs_to :team


  def self.recent
    days_ago = 6
    time_ago = days_ago.days.ago.getlocal
    where("created_at > ?", time_ago)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def index

  end

  def new
    @note = Note.new
    @team = current_user.current_team
  end

  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    if current_user.current_team
      @note.team_id = current_user.current_team.id # nil
    end

    if @note.save
      flash[:notice] = "Note Created!"
      redirect_to team_path(current_user.current_team.id)
    else
      flash[:error] = "Error in creating the Note.  Try Again."
      render :new
    end
  end

  def edit
  end

  def update
  end

  def show
  end

  def destroy
  end


  private

  def note_params
    params.require(:note).permit(:content)
  end

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/new.html.erb
<%= render partial: 'layouts/standings' %>



<div class='col-xs-12mod col-sm-12mod col-md-12mod main-div grass'>

  <h2>Create a Note</h2>

  <div class="row">
    <div class="col-md-8">
      <%= form_for @note, url: team_notes_path(@team.id) do |f| %>
        <% if @note.errors.any? %>
          <div class="alert alert-danger">
            <h4><%= pluralize(@note.errors.count, "error") %>.</hr>
              <ul>
                <% @note.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
          </div>
        <% end %>
        <%= form_group_tag(@note.errors[:content]) do %>
          <%= f.label :content %>
          <%= f.text_field :content, autofocus: true, class: 'form-control', placeholder:"Enter your note here." %>
        <% end %>

        <div class="form-group">
          <%= f.submit "Submit", class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>