config/routes.rb
Rails.application.routes.draw do
  resources :alerts
  get 'games/decide_game_view' => 'games#decide_game_view', as: :decide_game_view
  resources :games
  resources :game_hitting_stats
  resources :game_pitching_stats
  resources :locations
  resources :players
  get 'welcome/index'

  get 'welcome/about'

  resources :users do
    resources :players
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :teams do
    resources :notes
  end

  namespace :api do
    match '/texts', to: 'texts#preflight', via: [:options]
    resources :texts, only: [:create]

    match '/keepscore/teams', to: 'keep_scores#preflight', via: [:options]
    get 'keepscore/teams' => 'keep_scores#get_teams', as: :get_teams

    match '/keepscore/roster', to: 'keep_scores#preflight', via: [:options]
    get 'keepscore/roster' => 'keep_scores#get_roster', as: :get_roster

    match '/keepscore/post_game_stats', to: 'keep_scores#preflight', via: [:options]
    post 'keepscore/post_game_stats' => 'keep_scores#post_game_stats', as: :post_game_stats

  end

  mount ActionCable.server, at: '/cable'
  root 'welcome#index'
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :home, class_name: :Team
  belongs_to :visitors, class_name: :Team

  belongs_to :winner, class_name: :Team
  belongs_to :loser, class_name: :Team

  has_many :game_hitting_stats
  has_many :game_pitching_stats

  def determine_winner_loser
    if (self.home_runs > self.visitor_runs)
      self.winner = self.home
      self.loser = self.visitors
    end
    if (self.visitor_runs > self.home_runs)
    self.winner = self.visitors
      self.loser = self.home
    end
    self.save
  end


end

app/controllers/games_controller.rb
class GamesController < ApplicationController



  def index
    @games = Game.all
    @games_by_date = @games.group_by(&:date)
    @date = params[:date] ? Date.parse(params[:date]) : Date.today

  end

  def new
    @game = Game.new

  end

  def show
    @game = Game.find(game_id)
    @visitors = @game.visitors
    @home = @game.home

    @visitor_players = @visitors.players
    @home_players = @home.players


  end

  def decide_game_view
    @game = Game.find(game_id)

    if ((@game.winner.nil? || @game.loser.nil?) && applicable_team)
      redirect_to edit_game_path(@game)
    else
      redirect_to @game
    end
  end

  def edit
    @game = Game.find(params[:id])
    @team = applicable_team

    unless (@team.id == @game.home_id || @team.id == @game.visitors_id)
      flash[:notice] = "Game not finished and you aren't athorized to update this game!"
      redirect_to games_path
    end
    @players = @team.players
    @hitting_stats = @game.game_hitting_stats
    @hitting_stats_array = []
    @players.each do |p|
      @hitting_stats_array << @hitting_stats.find{|s| s.player_id == p.id}
    end



  end


  def update
    puts("in update")
    @game = Game.find(params[:id])

    @game.update(game_score_params)
    if @game.winner.nil? || @game.loser.nil?
      @game.determine_winner_loser
    end

    @team = applicable_team

    @team.determine_wins_loss_pct
    Team.determine_games_back

    @players = @team.players

    hitting = hitting_params

    hitting.each do |key, value|

      hitting_id = key.to_i
      hitting_stats = GameHittingStat.find(hitting_id)

      hitting_stats.ab = value[:ab].to_i
      hitting_stats.pa = value[:pa].to_i
      hitting_stats.single = value[:single].to_i
      hitting_stats.double = value[:double].to_i

      hitting_stats.triple = value[:triple].to_i
      hitting_stats.hr = value[:hr].to_i
      hitting_stats.bb = value[:bb].to_i
      hitting_stats.error = value[:error].to_i

      hitting_stats.fc = value[:fc].to_i
      hitting_stats.hb = value[:hb].to_i
      hitting_stats.wp = value[:wp].to_i
      hitting_stats.pb = value[:pb].to_i

      hitting_stats.sb = value[:sb].to_i
      hitting_stats.rbi = value[:rbi].to_i
      hitting_stats.r = value[:r].to_i
      hitting_stats.earned_run = value[:earned_run].to_i
      hitting_stats.sac = value[:sac].to_i
      hitting_stats.k = value[:k].to_i


      hitting_stats.save
    end
    puts("updated hitting")
    pitching = pitching_params
    if pitching
      pitching.each do |key, value|
        pitching_id = key.to_i
        pitching_stats = GamePitchingStat.find(pitching_id)
        pitching_stats.batters_retired = value[:batters_retired].to_i
        pitching_stats.r = value[:r].to_i
        pitching_stats.er = value[:er].to_i
        pitching_stats.sv = value[:sv].to_i
        pitching_stats.cg = value[:cg].to_i
        pitching_stats.bf = value[:bf].to_i
        pitching_stats.bb = value[:bb].to_i
        pitching_stats.h = value[:h].to_i
        pitching_stats.single = value[:single].to_i
        pitching_stats.double = value[:double].to_i
        pitching_stats.triple = value[:triple].to_i
        pitching_stats.hr = value[:hr].to_i
        pitching_stats.k = value[:k].to_i
        pitching_stats.wp = value[:wp].to_i
        pitching_stats.hb = value[:hb].to_i
        pitching_stats.bk = value[:bk].to_i
        pitching_stats.sb = value[:sb].to_i

        pitching_stats.save
      end
    end
    @game.save
    puts("updated pitching")
    @players.each do |player|
      calculate_hitting_totals(player)

      if player.positions.include?(Position.find(1))
        calculate_pitching_totals(player)
      end

    end
    puts("redirecting to team")
    redirect_to team_path(@team)


  end


  def create
    @game = Game.new(game_params)
    create_initial_game_stats(@game)
    puts @game.location_id
    puts @game.home_id



    if @game.save
      flash[:notice] = "New Game Scheduled!"
      redirect_to games_path
    else
      flash[:notice] = "Could Not Schedule a Game.  Try Again."
      redirect_to new_game_path
    end
  end

private





  def hitting_params
    hitting_hash = {}
    hitting_stats_hash = params['game_hitting_stats'].permit!.to_h
    hitting_stats_hash.each do |key, value|
      individual_hitting = hitting_stats_hash[key].symbolize_keys.slice(:ab, :pa, :single, :double, :tripple, :hr, :bb, :error, :fc, :hb, :wp, :pb, :sb, :rbi, :r, :earned_run, :sac, :k)
      hitting_hash[key] = individual_hitting


    end
    hitting_hash
  end

  def pitching_params
    pitching_hash = {}
    pitching_stats_hash = params['game_pitching_stats'].permit!.to_h
    if pitching_stats_hash
      pitching_stats_hash.each do |key, value|
        individual_pitching =
        pitching_stats_hash[key].symbolize_keys.slice(:batters_retired, :r, :er, :sv, :cg, :bf, :bb, :h, :single, :double, :triple, :hr, :k, :wp, :hb, :bk, :sb)
        pitching_hash[key] = individual_pitching
      end
      pitching_hash
    end
  end



  def game_params
      params.require(:game).permit(:home_id, :visitors_id, :location_id, :date, :time)
  end

  def game_id
    params.require(:id)
  end

  def game_score_params
    params.require(:game).permit(:home_runs, :home_hits, :home_errors, :visitor_runs, :visitor_hits, :visitor_errors)
  end

  def create_initial_game_stats(game)
    create_game_stats(game, game.home)
    create_game_stats(game, game.visitors)
    game.home_runs = 0
    game.home_hits = 0
    game.home_errors = 0
    game.visitor_runs = 0
    game.visitor_hits = 0
    game.visitor_errors = 0
  end


  def create_game_stats(game, team)
    team.players.each do |p|
      stat = GameHittingStat.new(game: game, player: p)
      stat.ab = 0
      stat.pa = 0
      stat.single = 0
      stat.double = 0
      stat.triple = 0
      stat.hr = 0
      stat.bb = 0
      stat.error = 0
      stat.fc = 0
      stat.hb = 0
      stat.wp = 0
      stat.pb = 0
      stat.sb = 0
      stat.rbi = 0
      stat.r = 0
      stat.earned_run = 0
      stat.sac = 0
      stat.k = 0
      stat.save

      if p.positions.include?(Position.find(1))
        pstat = GamePitchingStat.new(game: game, player: p)
        pstat.batters_retired = 0
        pstat.r = 0
        pstat.er = 0
        pstat.sv = 0
        pstat.cg = 0
        pstat.bf = 0
        pstat.bb = 0
        pstat.h = 0
        pstat.single = 0
        pstat.double = 0
        pstat.triple = 0
        pstat.hr = 0
        pstat.k  = 0
        pstat.wp = 0
        pstat.hb = 0
        pstat.bk = 0
        pstat.sb = 0
        pstat.cs = 0
        pstat.save
      end
    end
  end

  def calculate_pitching_totals(p)
    pitching_totals = PitchingTotal.find_by!(player_id: p.id)
    game_pitching_stats = GamePitchingStat.where(player_id: p.id)

    pitching_totals.w = 0
    pitching_totals.l = 0
    # note:  ip===innings pitched will be calculated by
    # batters retired divided by 3

    pitching_totals.ip = 0
    pitching_totals.r = 0
    pitching_totals.er = 0
    pitching_totals.g = 0
    pitching_totals.gs = 0
    pitching_totals.sv = 0
    pitching_totals.cg = 0
    pitching_totals.bf = 0
    pitching_totals.bb = 0
    pitching_totals.h = 0
    pitching_totals.b1 = 0
    pitching_totals.b2 = 0
    pitching_totals.b3 = 0
    pitching_totals.hr = 0
    pitching_totals.k = 0
    pitching_totals.wp = 0
    pitching_totals.hb = 0
    pitching_totals.bk = 0
    pitching_totals.sb = 0
    pitching_totals.cs = 0
    pitching_totals.batters_retired = 0

    pitching_totals.era = 0.000

    game_pitching_stats.each do |ps|
      pitching_totals.batters_retired += ps.batters_retired
      pitching_totals.r += ps.r
      pitching_totals.er += ps.er
      if ps.bf > 0
       pitching_totals.g += 1
      end

      # need to create a game started game_pitching_stat
      #pitching_totals.gs += ps.gs


      pitching_totals.sv += ps.sv
      pitching_totals.cg += ps.cg
      pitching_totals.bf += ps.bf
      pitching_totals.bb += ps.bb
      pitching_totals.h += ps.h
      pitching_totals.b1 += ps.single
      pitching_totals.b2 += ps.double
      pitching_totals.b3 += ps.triple
      pitching_totals.hr += ps.hr
      pitching_totals.k += ps.k
      pitching_totals.wp += ps.wp
      pitching_totals.hb += ps.hb
      pitching_totals.bk += ps.bk
      pitching_totals.sb += ps.sb
      pitching_totals.cs += ps.cs

    end
    pitching_totals.save


    unless pitching_totals.batters_retired == 0
      pitching_totals.era = pitching_totals.er.fdiv(pitching_totals.batters_retired)*27
    end

    pitching_totals.save



  end




  def calculate_hitting_totals(p)
    hitting_totals = HittingTotal.find_by!(player_id: p.id)
    game_hitting_stats = GameHittingStat.where(player_id: p.id)

    hitting_totals.g = 0
    hitting_totals.pa = 0
    hitting_totals.ab = 0
    hitting_totals.h = 0
    hitting_totals.bb = 0
    hitting_totals.b1 = 0
    hitting_totals.b2 = 0
    hitting_totals.b3 = 0
    hitting_totals.hr = 0
    hitting_totals.k =  0
    hitting_totals.sf = 0
    hitting_totals.err = 0
    hitting_totals.hb = 0
    hitting_totals.rbi = 0
    hitting_totals.r = 0
    hitting_totals.sb = 0
    hitting_totals.cs = 0
    hitting_totals.ave = 0.000
    hitting_totals.obp = 0.000
    hitting_totals.slg = 0.000

    game_hitting_stats.each do |gs|
      hitting_totals.pa = hitting_totals.pa + gs.pa

      hitting_totals.ab = hitting_totals.ab + gs.ab
      hitting_totals.bb = hitting_totals.bb + gs.bb
      hitting_totals.b1 = hitting_totals.b1 + gs.single
      hitting_totals.b2 = hitting_totals.b2 + gs.double
      hitting_totals.b3 = hitting_totals.b3 + gs.triple
      hitting_totals.hr = hitting_totals.hr + gs.hr
      hitting_totals.k = hitting_totals.k + gs.k
      hitting_totals.sf = hitting_totals.sf + gs.sac
      hitting_totals.err = hitting_totals.err + gs.error
      hitting_totals.hb = hitting_totals.hb + gs.hb
      hitting_totals.rbi = hitting_totals.rbi + gs.rbi

app/helpers/games_helper.rb
# Based on Ryan Bates RailsCasts 213 Calendars (revised) http://railscasts.com/episodes/213-calendars-revised?autoplay=true



module GamesHelper

  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
    START_DAY = :sunday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: 'calendar' do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map {|day| content_tag :th, day }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map {|day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      classes = []
      classes << "today" if day == Date.today
      classes << "notmonth" if day.month != date.month
      classes.empty? ? nil : classes.join('')
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/views/games/_games_tabs.html.erb
<!-- Will need to update the condition here so that only admin users can Add a Game  -->
<% if current_user && current_user.current_team %>
<!--  -->
  <div class="row">
    <ul class="nav nav-tabs">

      <li><%= link_to "Add a Game", new_game_path %></li>

    </ul>
  </div>
<% end %>

app/views/games/edit.html.erb
<%= render partial: 'layouts/standings' %>


<div class='col-xs-12mod col-sm-12mod col-md-12mod main-div grass'>



<%= form_tag(game_path, method: "put") do %>
  <div class='col-xs-12 col-sm-12 col-md-10'>
    <row class='col-md-12 left-margin-10px stats-table'>
     <div class='col-md-6'>


      <table class="table table-responsive score-table">
        <thead>
          <tr>
            <th></th>
            <th><h3 class='RHE'>R</h3></th>
            <th><h3 class='RHE'>H</h3></th>
            <th><h3 class='RHE'>E</h3></th>
          </tr>
        </thead>



        <tbody>
        <%= fields_for 'game', @game do |g| %>

            <tr>
              <td>
                <h3 class='team-score'><%= @game.visitors.name %></h3>
              </td>
              <td> <h3 class='team-score'>
                  <%= g.number_field :visitor_runs, min: 0, class: 'field form-control'%>
                </h3>
              </td>
              <td><h3 class='team-score'><%= g.number_field :visitor_hits, min: 0, class: 'field form-control'%></h3>
              </td>
              <td><h3 class='team-score'><%= g.number_field :visitor_errors, min: 0, class: 'field form-control'%></h3>
              </td>
            </tr>
            <tr>
              <td>
                <h3 class='team-score'><%= @game.home.name %></h3>
              </td>
              <td>
                  <h3 class='team-score'><%= g.number_field :home_runs, min: 0, class: 'field form-control'%></h3>
              </td>
              <td>
                  <h3 class='team-score'><%= g.number_field :home_hits, min: 0, class: 'field form-control'%></h3>
              </td>
              <td>
                  <h3 class='team-score'><%= g.number_field :home_errors, min: 0, class: 'field form-control'%></h3>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</row>

<row class='col-md-12 left-margin-10px stats-table'>
  <table class="table table-striped table-responsive">
    <thead>
      <tr>
            <th>Name</th>
            <th>AB</th>
            <th>PA</th>
            <th>1b</th>
            <th>2b</th>
            <th>3b</th>
            <th>Hr</th>
            <th>BB</th>
            <th>E</th>
            <th>FC</th>
            <th>HB</th>
            <th>SB</th>
            <th>RBI</th>
            <th>R</th>
            <th>ER</th>
            <th>SAC</th>
            <th>K</th>
      </tr>

    <tbody>

<!-- <row class='col-md-12'> -->
  <% @players.each_with_index do  |player, i| %>
    <%= fields_for 'players[]', player do |p| %>
    <!-- -->
      <% player_hitting_stats = player.game_hitting_stats.find{|hs| hs.game_id == @game.id} %>
      <% if player_hitting_stats %>
        <%= p.hidden_field(:id) %>
        <%= fields_for 'game_hitting_stats[]', player_hitting_stats do |f| %>
          <tr>
              <td class='col-md-2'> <%= player.last_name %> </td>

              <td><%= f.number_field :ab, min: 0, class: 'col-md-3 stats-input' %></td>
              <td><%= f.number_field :pa, min: 0, class: 'col-md-3 stats-input'%></td>
              <td><%= f.number_field :single, min: 0, class: 'col-md-3 stats-input' %></td>
              <td><%= f.number_field :double, min: 0, class: 'col-md-3 stats-input'%></td>
              <td><%= f.number_field :triple, min: 0, class: 'col-md-3 stats-input' %></td>
              <td><%= f.number_field :hr, min: 0, class: 'col-md-3 stats-input'%></td>
              <td><%= f.number_field :bb, min: 0, class: 'col-md-3 stats-input' %></td>
              <td><%= f.number_field :error, min: 0, class: 'col-md-3 stats-input'%></td>
              <td><%= f.number_field :fc, min: 0, class: 'col-md-3 stats-input' %></td>
              <td><%= f.number_field :hb, min: 0, class: 'col-md-3 stats-input'%></td>
              <td><%= f.number_field :sb, min: 0, class: 'col-md-3 stats-input' %></td>
              <td><%= f.number_field :rbi, min: 0, class: 'col-md-3 stats-input'%></td>

              <td><%= f.number_field :r, min: 0, class: 'col-md-3 stats-input' %></td>
              <td><%= f.number_field :earned_run, min: 0, class: 'col-md-3 stats-input'%></td>
              <td><%= f.number_field :sac, min: 0, class: 'col-md-3 stats-input' %></td>
              <td><%= f.number_field :k, min: 0, class: 'col-md-3 stats-input'%></td>
          </tr>
        <% end %>
       <% end %>

    <% end %>
  <% end %>

  </tbody>
  </table>
</row>

<row class='col-md-12 left-margin-10px stats-table'>
  <table class='table table-striped table-responsive'>
    <thead>
      <tr>
          <th>Name</th>
          <th>Retired</th>
          <th>R</th>
          <th>ER</th>
          <th>SV</th>
          <th>CG</th>
          <th>BF</th>
          <th>BB</th>
          <th>H</th>
          <th>1B</th>
          <th>2B</th>
          <th>3B</th>
          <th>HR</th>
          <th>K</th>
          <th>WP</th>
          <th>HB</th>
          <th>BK</th>
          <th>SB</th>
      </tr>
    </thead>

    <tbody>
      <% @players.each_with_index do  |player, i| %>
        <% if player.positions.include?(Position.find(1)) %>
          <%= fields_for 'players[]', player do |p| %>
            <% player_pitching_stats = player.game_pitching_stats.find{|ps| ps.game_id == @game.id} %>
            <%= p.hidden_field(:id) %>

            <% if player_pitching_stats %>
              <%= fields_for 'game_pitching_stats[]', player_pitching_stats do |f| %>
                <tr>
                  <td><%= player.last_name %></td>
                  <td><%= f.number_field :batters_retired, min: 0, class: 'col-md-3 stats-input' %></td>
                  <td><%= f.number_field :r, min: 0, class: 'col-md-3 stats-input'%></td>
                  <td><%= f.number_field :er, min: 0, class: 'col-md-3 stats-input' %></td>
                  <td><%= f.number_field :sv, min: 0, class: 'col-md-3 stats-input' %></td>
                  <td><%= f.number_field :cg, min: 0, class: 'col-md-3 stats-input'%></td>
                  <td><%= f.number_field :bf, min: 0, class: 'col-md-3 stats-input'%></td>
                  <td><%= f.number_field :bb, min: 0, class: 'col-md-3 stats-input'%></td>
                  <td><%= f.number_field :h, min: 0, class: 'col-md-3 stats-input'%></td>
                  <td><%= f.number_field :single, min: 0, class: 'col-md-3 stats-input' %></td>
                  <td><%= f.number_field :double, min: 0, class: 'col-md-3 stats-input'%></td>
                  <td><%= f.number_field :triple, min: 0, class: 'col-md-3 stats-input' %></td>
                  <td><%= f.number_field :hr, min: 0, class: 'col-md-3 stats-input'%></td>
                  <td><%= f.number_field :k, min: 0, class: 'col-md-3 stats-input' %></td>
                  <td><%= f.number_field :wp, min: 0, class: 'col-md-3 stats-input'%></td>
                  <td><%= f.number_field :hb, min: 0, class: 'col-md-3 stats-input'%></td>
                  <td><%= f.number_field :bk, min: 0, class: 'col-md-3 stats-input' %></td>
                  <td><%= f.number_field :sb, min: 0, class: 'col-md-3 stats-input'%></td>
                </tr>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</row>

<row class='col-md-12 left-margin-10px stats-table'>
  <%= submit_tag "Save", class: 'btn btn-success' %>
</row>
<% end %>

</div>

app/views/games/index.html.erb
<%= render partial: 'layouts/standings' %>


  <div class='col-xs-12mod col-sm-12mod col-md-12mod main-div grass'>
    <div class='margin-15px'>
      <div id='schedule'>
        <h2 id='month'>
          <%= link_to '<', date: @date.prev_month %>
          <%= @date.strftime('%B %Y') %>
          <%= link_to'>', date: @date.next_month %>
        </h2>
        <%= calendar @date do |date| %>
          <%= date.day %>
          <% if @games_by_date[date] %>
            <ul>
              <% @games_by_date[date].each do |g| %>
                <li><%= link_to "#{g.visitors.name} v. #{g.home.name}", decide_game_view_url(id: g) %></li>
              <% end %>
            </ul>
          <% end %>
        <% end %>
      </div>

      <%= render partial: 'games/games_tabs' %>
    </div>
  </div>

app/views/games/new.html.erb
<%= render partial: 'layouts/standings' %>


<div class='col-xs-12mod col-sm-12mod col-md-12mod main-div grass'>

  <h3>Schedule a new game </h3>


    <%= form_for [@game] do |g| %>
      <div class="col-md-4 form-group">
        <row class='form-control'>
          <div class='col-md-6'>
            <%= g.label :visitors_id, "Visitors" %>
          </div>
          <div class='col-md-6'>
            <%= g.collection_select :visitors_id, Team.order(:name), :id, :name, include_blank: true %>
          </div>
        </row>

        <row class='form-control'>
          <div class='col-md-6'>
            <%= g.label :home_id, "Home" %>
          </div>
          <div class='col-md-6'>
            <%= g.collection_select :home_id, Team.order(:name), :id, :name, include_blank: true %>
          </div>
        </row>
      </div>


      <div class="col-md-4 form-group">
        <%= g.date_field :date, class: 'form-control'%>
        <%= g.time_field :time, class: 'form-control'%>
      </div>


      <div class='col-md-4'>
        <div class="form-group">
          <row class='form-control'>
            <div class='col-md-6'>
              <%= g.label :location_id, "Location" %>
            </div>
            <div class='col-md-6'>
              <%= g.collection_select :location_id, Location.order(:name), :id, :name, include_blank: true %>
            </div>
          </row>
        </div>
      </div>
    <div class='row'>
      <div class='col-md-12'>
        <div class='col-md-4'>
          <%= g.submit "Save", class: 'btn btn-success' %>
        </div>
      </div>
    </div>
  <% end %>

</div>

app/views/games/update.html.erb
Game update
<%= @game.visitor_runs %>