config/routes.rb
Rails.application.routes.draw do
  resources :alerts
  get 'games/decide_game_view' => 'games#decide_game_view', as: :decide_game_view
  resources :games
  resources :game_hitting_stats
  resources :game_pitching_stats
  resources :locations
  resources :players
  get 'welcome/index'

  get 'welcome/about'

  resources :users do
    resources :players
  end

  resources :sessions, only: [:new, :create, :destroy]
  resources :teams do
    resources :notes
  end

  namespace :api do
    match '/texts', to: 'texts#preflight', via: [:options]
    resources :texts, only: [:create]

    match '/keepscore/teams', to: 'keep_scores#preflight', via: [:options]
    get 'keepscore/teams' => 'keep_scores#get_teams', as: :get_teams

    match '/keepscore/roster', to: 'keep_scores#preflight', via: [:options]
    get 'keepscore/roster' => 'keep_scores#get_roster', as: :get_roster

    match '/keepscore/post_game_stats', to: 'keep_scores#preflight', via: [:options]
    post 'keepscore/post_game_stats' => 'keep_scores#post_game_stats', as: :post_game_stats

  end

  mount ActionCable.server, at: '/cable'
  root 'welcome#index'
end

app/models/alert.rb
class Alert < ApplicationRecord
  belongs_to :user

  def self.active
    days_ago = 2
    time_ago = days_ago.days.ago.getlocal

    # minutes_ago = 10
    #
    # time_ago = minutes_ago.minutes.ago.getlocal
    where("created_at > ?", time_ago)
  end

end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :home, class_name: :Team
  belongs_to :visitors, class_name: :Team

  belongs_to :winner, class_name: :Team
  belongs_to :loser, class_name: :Team

  has_many :game_hitting_stats
  has_many :game_pitching_stats

  def determine_winner_loser
    if (self.home_runs > self.visitor_runs)
      self.winner = self.home
      self.loser = self.visitors
    end
    if (self.visitor_runs > self.home_runs)
    self.winner = self.visitors
      self.loser = self.home
    end
    self.save
  end


end

app/models/hitting_total.rb
class HittingTotal < ApplicationRecord
  belongs_to :player

  def set_initial_totals
    self.g = 0
    self.pa = 0
    self.ab = 0
    self.h = 0
    self.bb = 0
    self.b1 = 0
    self.b2 = 0
    self.b3 = 0
    self.hr = 0
    self.k =  0
    self.sf = 0
    self.err = 0
    self.hb = 0
    self.rbi = 0
    self.r = 0
    self.sb = 0
    self.cs = 0
    self.ave = 0.000
    self.obp = 0.000
    self.slg = 0.000
  end
end

app/models/location.rb
class Location < ApplicationRecord
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  belongs_to :team


  def self.recent
    days_ago = 6
    time_ago = days_ago.days.ago.getlocal
    where("created_at > ?", time_ago)
  end
end

app/models/pitching_total.rb
class PitchingTotal < ApplicationRecord
  belongs_to :player


  def set_initial_totals

    self.w = 0
    self.l = 0
    self.ip = 0
    self.r = 0
    self.er = 0
    self.g = 0
    self.gs = 0
    self.cg = 0
    self.sv = 0
    self.bf = 0
    self.bb = 0
    self.h = 0
    self.b1 = 0
    self.b2 = 0
    self.b3 = 0
    self.hr = 0
    self.k = 0
    self.wp = 0
    self.hb = 0
    self.bk = 0
    self.sb = 0
    self.cs = 0

    self.era = 0.000

  end
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
  has_one :hitting_total
  has_one :pitching_total
  has_and_belongs_to_many :positions

  has_many :game_hitting_stats
  has_many :game_pitching_stats



  enum bats: [:bats_left, :bats_right, :switch_hitter]
  # will allow player.bats = 'bats_left'
  # player.bats_left? #=> true
  enum throws: [:throws_left, :throws_right]


  def self.on_team(team)
    where("team_id =?", team)
  end

  def pitcher?
    self.positions.include?(Position.find_by(id: 1))
  end

end

app/models/players_position.rb
class PlayersPosition < ApplicationRecord
  belongs_to :player
  belongs_to :position
end

app/models/position.rb
class Position < ApplicationRecord
  has_and_belongs_to_many :players
end

app/models/roster.rb
class Roster < ApplicationRecord
  belongs_to :user
  belongs_to :team

  validates :team_id, presence: true
  validates :user_id, presence: true

  # after_save :set_other_rosters_to_false, if: :manager?
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :rosters
  has_many :users, :through => :rosters
  has_many :notes
  has_many :players

  has_many :home_teams, class_name: :Game, foreign_key: :home_id
  has_many :visitor_teams, class_name: :Game, foreign_key: :visitors_id
  has_many :winners, class_name: :Game, foreign_key: :winner_id
  has_many :losers, class_name: :Game, foreign_key: :loser_id



  def determine_wins_loss_pct
    games = []

    Game.where(visitors: self.id).find_each do |g|
      games << g
    end
    Game.where(home: self.id).find_each do |g|
      games << g
    end
    wins = 0
    losses = 0
    games.each do |g|
      if g.winner_id == self.id
        wins += 1
      end
      if g.loser_id == self.id
        losses += 1
      end
    end
    self.wins = wins
    self.losses = losses
    self.winning_percentage = self.wins.fdiv(self.wins + self.losses)
    self.save

  end

  




  def self.determine_games_back
    teams = Team.order(winning_percentage: :desc)
    first_place = teams[0]
    teams.each do |t|
      games_back = ((first_place.wins - t.wins).abs + (t.losses - first_place.losses).abs).fdiv(2).round(1)
      t.games_back = games_back
      t.save
    end

  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :rosters
  has_many :teams, :through => :rosters
  has_many :notes

  before_save {self.email = email.downcase}

  before_save {self.cell = cell.gsub(/[^\d]/, "")}

  cell_REGEX = /\A(\d){3}\-(\d){3}\-(\d){4}\z/
  email_REGEX = /\A((\w)+(\.)?)*(\w)+@{1}((\w)+(\.)?)*(\w)+(\.){1}(com|io|org|biz)\z/i

  validates :first_name, presence: true
  validates :cell, presence: true, uniqueness: {case_sensitive: false}, format: {with: cell_REGEX}
  validates :password, presence: true, length: {minimum: 6}, if: "password_digest.nil?"

  validates :email,
            presence: true,
            uniqueness: {case_sensitive: false},
            format: {with: email_REGEX}

  has_secure_password

  def current_team
    self.teams.order("created_at").last
  end

  def manager
    self.rosters.find_by(user_id: self.id, manager: true)

  end




end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/helpers/games_helper.rb
# Based on Ryan Bates RailsCasts 213 Calendars (revised) http://railscasts.com/episodes/213-calendars-revised?autoplay=true



module GamesHelper

  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
    START_DAY = :sunday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: 'calendar' do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map {|day| content_tag :th, day }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map {|day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day)
    end

    def day_classes(day)
      classes = []
      classes << "today" if day == Date.today
      classes << "notmonth" if day.month != date.month
      classes.empty? ? nil : classes.join('')
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   def create_session(user)
     session[:user_id] = user.id
   end

   def destroy_session(user)
     session[:user_id] = nil
   end

   def current_user
     User.find_by(id: session[:user_id])
   end



end

app/helpers/teams_helper.rb
module TeamsHelper

  def applicable_team
    if current_user
      current_user.teams.order("created_at").last
    else
      false
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def current_team
    self.teams.order("created_at").last
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper

  




end

app/views/layouts/_standings.html.erb
<% standings %>

<div class='col-xs-12mod col-sm-8mod col-md-8mod main-div grass'>

  <div class='col-xs-12 col-sm-12 col-md-4'>
    <table class='table table-striped table-responsive'>
      <thead>
        <tr>
          <th></th>
          <th><h5>W</h5></th>
          <th><h5>L</h5></th>
          <th><h5>Pct.</h5></th>
          <th><h5>GB</h5></th>
        </tr>
      </thead>
      <tbody>
        <% @teams.each do |t| %>
          <tr>
            <td><%= link_to t.name, t %></td>
            <td><%= t.wins %></td>
            <td><%= t.losses %></td>

            <% if t.winning_percentage %>
              <td><%= t.winning_percentage %></td>
            <% else %>
              <td>-</td>
            <% end %>

            <% if t.games_back %>
              <td><%= t.games_back %></td>
            <% else %>
              <td>-</td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlayBall</title>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  <div class="container">
        <ul class="nav nav-tabs">
          <li><%= link_to "Home", welcome_index_path %></li>
          <li><%= link_to "About", welcome_about_path %></li>
          <li><%= link_to "Keep Score", "https://frozen-savannah-54849.herokuapp.com" %></li>
          <!-- <li><%= link_to "Keep Score", "http://localhost:3001" %></li>-->
          <!-- <li id='keep-score'><%= link_to "Keep Score", "" %></li> -->
          <li><%= link_to "Schedule", games_path %></li>
          <li id='sendTxt'><%= link_to "Send a Text Alert!", ""%></li>

          <li><button type='button' class='btn btn-info btn-lg alertTab-padding' style='display: <%=show_alerts?%>' id='alerts'><span class='glyphicon glyphicon-alert'></span>Alerts</button>
          </li>

          <div class="pull-right user-info">
            <% if current_user %>
                 At Bat: <strong><%= current_user.first_name %></strong>
                 <%= link_to "Sign Out", session_path(current_user), method: :delete %>

              <% else %>
                 <%= link_to "Register", new_user_path %> - <%= link_to "Sign In", new_session_path %>
          <% end %>
          </div>


        </ul>

      <div class="flash">
        <% if flash[:notice] %>
            <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <%= flash[:notice] %>
            </div>
        <% elsif flash[:error] %>
            <div class="alert alert-danger alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <%= flash[:error] %>
            </div>

        <% elsif flash[:alert] %>

            <div class ="alert alert-warning alert-dismissible">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <%= flash[:alert] %>
            </div>
        <% end %>


      </div>


          <div class="flash" style='display: <%=show_alerts?%>' id='alertBox'>
              <div class = "alert alert-warning alert-dismissible " id='alertList'>
                  <button type="button" class="close" data-hide="alert" id='alertListClose'>&times;</button>
                  <% Alert.active.each do |a| %>
                    <p><%= a.content %></p>
                  <% end %>
              </div>
          </div>


        <div class='row'>
          <div class="col-xs-12mod col-sm-4 col-md-4 main-div dirt">
            <%= image_tag("CABL-BRICK-WALLA1.png", class: "cabl-img") %>
          </div>

          <%= yield %>
        </div>

    <footer>
        &copy; Copyright <%= DateTime.now.year %> hac-jac algorithms
    </footer>
  </div>

</body>

</html>